export const CONFIG = {
  OVERALL: {
    QUANTITY: 207,
    ADDITION_RATIO: 0.6,
    SUBTRACTION_RATIO: 0.4,
  },
  ADDITION: {
    MAX_LIMIT_OF_RESULT: 9999,
    MIN_NUM: 99,
    MAX_NUM: 999,
  },
  SUBTRACTION: {
    MIN_LIMIT_OF_RESULT: 0,
    MAX_LIMIT_OF_RESULT: 9999,
    MIN_NUM: 1,
    MAX_NUM: 20,
  },
} as const;
